version: '3.7'

services:
    db:
        image: mysql
        container_name: gpt-mysql
        ports:
            - "3306:3306"
        command: mysqld --default-authentication-plugin=mysql_native_password
        volumes:
        - db-volume:/var/lib/mysql
        - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
        
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: gpt_voice
            MYSQL_USER: admin
            MYSQL_PASSWORD: 12345
            
        
        networks:
            - backend
#    main:
#      container_name: gpt-api
#      build:
#        context: ./docker/
#        target: development
#      volumes:
#        - .:/usr/src/app
#        - /node_modules
#      ports:
#        - 8081:80
#      command: npm run start:dev
#      env_file:
#        - .env
#      networks:
#        - backend   
volumes:
    db-volume:

networks:
    backend:
