FROM node:18.16.0-alpine As development

WORKDIR /gpt_voice/gpt_voice_api

COPY package.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:18.16.0-alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /

COPY package*.json ./

RUN npm install --only=production

COPY . .

COPY --from=development /dist ./dist

CMD ["node", "dist/main"]

#FROM node:18.16.0-alpine
#WORKDIR /usr/src/app

#RUN apt-get update && apt-get upgrade -y

#COPY package*.json ./

#RUN npm install

#COPY . .

#RUN npm run start:dev

#EXPOSE 8080

